### PR TITLE
Update packaging-app-for-distribution.md

### PR DESCRIPTION
**Pull request by Kacper-OS**

### CODE REVIEW

**Comment by taaaf11** [comment]
I don't want to disturb you in any sense, but, in general, scripts are not "thought" to be run as administrator. This will add an impact to the user's mind.

**Comment by Kacper-OS** [comment]
yeah, it can be confusing, but it's another way of building app

**Comment by taaaf11** [comment]
> yeah, it can be confusing, but it's another way of building app

I agree. Now this is the point where project head comes.

**Comment by taaaf11** [comment]
> Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/flet-dev/website?pullRequest=235) before we can accept your contribution.

@Kacper-OS have you signed the contributor license agreement?

**Comment by Kacper-OS** [comment]
No, but I was thinking and I will close this PR

**Pull request closed without merging**
