### PR TITLE
Added Emoji Enigma to Gallery

### PR DESCRIPTION
**Pull request by vihutuo**
Emoji Enigma is an emoji game made using Flet. Try to guess 20 words using the emote icons as clues. 
This app was made by teachers and students of Class 12 from Little Star Higher Secondary School, Nagaland, India  as part of their class presentation for 2023. 

Link to app : https://ee.lshss.app/

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Is https://github.com/vihutuo/emoji_riddles a private repository? I'm getting 404.

**Comment by vihutuo** [comment]
> Is https://github.com/vihutuo/emoji_riddles a private repository? I'm getting 404.

Sorry, I have made it public now

**Comment by FeodorFitsner** [comment]
Thank you! Oh, and put license file in the root. Without the license the repo is not even allowed to be cloned ;)

**Comment by vihutuo** [comment]
Added License. Thanks

**Comment by FeodorFitsner** [comment]
Lovely app! I've enjoined playing it :) thank you for your contribution!

**Comment by vihutuo** [comment]
Thank You. We have enjoyed working on the Flet framework. It has been a wonderful experience

**Pull request merged**
