### PR TITLE
Update todo tutorial documentation to match example code

### PR DESCRIPTION
**Pull request by BrianOliphant**
Corrected differences between document example changes and code from github.

### CODE REVIEW

**Comment by DavMelchi** [comment]
I think it should be the other way around... Update the code on github as the docs by using **import flet as ft** specially 🤔

**Comment by FeodorFitsner** [comment]
Was going to comment the same :)

**Comment by BrianOliphant** [comment]
I've reverted flet as ft, however I think that importing the individual components is very helpful for new learners such as myself.

**Comment by DavMelchi** [comment]
Ok I understand that it may be easier to understand for a beginner but to be more pythonic it's better **import flet as ft**.  Also as I said earlier, the documentation does not need to be changed.  Rather, it's the example code on github that needs to be updated to maintain consistency. 🙂

**Comment by BrianOliphant** [comment]
They need to match, I just chose to do the documentation since it was something I had never done before and thought it would be good to have a bit more experience with. As someone with more knowledge and experience with this then me, do what you think is best.

**Comment by DavMelchi** [comment]
In my opinion you have enough experience already to do so.  I think, you can close this PR and  open new one with update the github example instead to match the doc.  Please try it🙂

**Comment by trentoliphant** [comment]
There are two things here that I think are being confused - one is the use of `import flet as ft` vs `import flet` and the the other is the `from flet import ([list of compenents])`.    The update commit has changed things back to the `import flet as ft` - but also imports the components separately.  

Do you have an objection to this?  

This is also the style of the code in https://github.com/flet-dev/examples/blob/main/python/apps/todo/todo.py

**Pull request closed without merging**
