### PR TITLE
Alphabetical sorting

### PR DESCRIPTION
**Pull request by ndonkoHenri**
I went through the pages of all controls, and carefully took time to sort all the properties/events alphabetically. This will help the docs be better organized and hence make searched properties easy to find. Alphabetical sorting is very common in popular documentations.
If this PR is merged, everyone updating (making a PR to) this repo (adding new properties or controls) should also try his/her best to sort alphabetically... for consistency everywhere.
I also made some very minor fixes along the line: updated some code blocks(import flet as ft) and fixed some typos

It might not be an easy task for anyone reviewing my changes, so I propose to check the total number of lines in each of the files I touched/modified. Because I wasn't adding anything new, the total number of lines in each modified file before and after my PR should definitely be equal. (some have a slight diff of one because of removal or addition of the/a last line(whiteline? whitespace?))

You could even try deploying a test website as you used to do, so we could better have a look at the changes.
Let me know how you find my idea, or if there is any issue. :)

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Indeed, trying to diff changes is completely pointless :)

I'll configure a test branch.

image

**Comment by ndonkoHenri** [comment]
Alright. 👍🏾

**Comment by FeodorFitsner** [comment]
I've checked PR locally. Looked good to me!

Fantastic work! How did you do that? Manually?! :)

**Comment by ndonkoHenri** [comment]
Yes, manually to minimize mistakes.
I had all the ascii letters on the side, as reference for quick sorting.

**Pull request merged**
