### PR TITLE
Update navigationbar.md

### PR DESCRIPTION
**Pull request by Benitmulindwa**
replaced `ControlState` by `MaterialState`

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Thanks for your PRs! Could you not create a new PR for every change please, but combine everything in one?

**Comment by ndonkoHenri** [comment]
Why are you doing this @Benitmulindwa ?
`MaterialState` is now deprecated and has been replaced by `ControlState`, as I [mentioned](https://python.plainenglish.io/whats-new-in-flet-v0-23-0-25613d742db9#:~:text=MaterialState%20enum%20is-,deprecated,-and%20has%20been) in the release of 0.23.0

**Comment by Benitmulindwa** [comment]
@ndonkoHenri  ooh!! didn't know that,... thought I was using the latest flet version and was not getting `ControlState`. My bad!, I was using 0.22.0 version. 😑

**Comment by ndonkoHenri** [comment]
Sorry for that.

**Pull request closed without merging**
