### PR TITLE
Gallery v1

### PR DESCRIPTION
**Pull request by FeodorFitsner**

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
I think there should also be one gallery to showcase community made stuffs. 
Wdyt?

**Comment by FeodorFitsner** [comment]
I think we are going to have a single gallery for both flet and community apps. We could introduce tags to distinguish.
When I publish Gallery v1 I'm going to make an announcement and ask people to contribute. You can start preparing your apps already :)

**Comment by ndonkoHenri** [comment]
Great idea.
Here are some useful infos to be shown; `App name, description, preview image, repo link, author's name, link to online app`
Inspiration: https://streamlit.io/gallery

**Comment by ndonkoHenri** [comment]
image

**Comment by FeodorFitsner** [comment]
Let's start from something simple and then add more info :)

**Pull request merged**
