### PR TITLE
fix a broken link

### PR DESCRIPTION
**Pull request by Benitmulindwa**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
I'm not getting a broken link there. What browser are you seeing it in?

**Comment by Benitmulindwa** [comment]
I'm on Microsoft Edge,... Actually, every **ShaderMask.blend_mode** link is broken

**Comment by FeodorFitsner** [comment]
Looking at your URL in the screenshot I'd say the fix would be changing that URL to absolute. Adding `.md` wont fix that.

**Comment by Benitmulindwa** [comment]
oooh! my bad, I'm going to fix it!

**Pull request closed without merging**
