### PR TITLE
Password Strength checker

### PR DESCRIPTION
**Pull request by LineIndent**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Do you have a live working demo hosted somewhere?

**Comment by LineIndent** [comment]
No, it's not being hosted anywhere and I don't have a live demo.

**Comment by FeodorFitsner** [comment]
If you want us to host your example submit your app to this repo under "community": https://github.com/flet-dev/examples/tree/main/python/community

**Comment by LineIndent** [comment]
Done. Thank you!

**Pull request closed without merging**
