### PR TITLE
More Screenshots

### PR DESCRIPTION
**Pull request by ndonkoHenri**
Some more screenshots for the docs.

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Let me know when it's ready to merge.

**Comment by ndonkoHenri** [comment]
Hey @FeodorFitsner, any updates here?
It is merged, but not yet live.

**Comment by FeodorFitsner** [comment]
It should be published automatically when merged into main.

**Comment by FeodorFitsner** [comment]
e.g. https://github.com/flet-dev/website/pull/57/files#diff-3c95f304272ccbb29e1af0fa99093dcadb1b21ad1d71af204b3c5748799fcdf6
Published here: https://flet.dev/docs/controls/appbar

**Comment by ndonkoHenri** [comment]
Oh, I saw them now.
To be reviwed:
https://flet.dev/docs/controls/circleavatar (image too big - needs to be reduced)
https://flet.dev/docs/controls/navigationrail (image seems to small - needs to be increased)

**Pull request merged**
