### PR TITLE
More screenshots

### PR DESCRIPTION
**Pull request by FeodorFitsner**

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/guides/python/getting-started

https://flet.dev/docs/controls/verticaldivider/

https://flet.dev/docs/controls/divider

There seems to be an issue with the images here.

**Comment by FeodorFitsner** [comment]
I see there are broken images on divider pages.

What issue do you see on https://flet.dev/docs/guides/python/getting-started though, could you drop a screenshot?

**Comment by ndonkoHenri** [comment]
Oh, sorry, seems like there are no errors there.
Just the divider pages for now.

**Comment by ndonkoHenri** [comment]
Oh, sorry, seems like there are no errors there.
Just the divider pages for now.

**Comment by ndonkoHenri** [comment]
https://flet.dev/docs/controls/alertdialog
Seems to be a broken link to the image/gif..
Am i right?

**Comment by FeodorFitsner** [comment]
yep

**Pull request merged**
