### PR TITLE
deployment instructions to Cloudflare Pages

### PR DESCRIPTION
**Pull request by ndonkoHenri**
Let me know if there's anything to be modified.

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Could you please move images to a sub-directory here: https://github.com/flet-dev/website/tree/main/static/img/docs to host them with a website?

**Comment by ndonkoHenri** [comment]
Alright.
Will do that.
I saw this: https://github.com/flet-dev/website/blob/main/static/img/docs/callout-demo.gif
You forgot to document it?

**Comment by ndonkoHenri** [comment]
I didn't use the `yarn`. I haven't downloaded it yet.
So, let me know if there is anything I should add or modify.

**Comment by ndonkoHenri** [comment]
By the way, remember to update the roadmap. (Check ✅ what has already been done)

**Comment by ndonkoHenri** [comment]
Going to go have a look at deployment on vercel. 😉

**Comment by FeodorFitsner** [comment]
Cool! And we could describe GitHub too as I tried it and it worked.

**Pull request merged**
