### PR TITLE
All screenshots are static images (.png) now and the images are compressed in size.

### PR DESCRIPTION
**Pull request by techemmy**
By the way, I only synced my fork with the original repository, but it added the synced change as my commit. I'm confused about that.

### CODE REVIEW

**Comment by techemmy** [comment]
Oh! Sorry, I forgot to make a PR to the more-screenshot branch :(

**Comment by techemmy** [comment]
Changing the target base branch for the PR is causing some conflicts.

**Comment by FeodorFitsner** [comment]
Looks nicer, thank you! And I see you added screenshots to other sections too!

One last thing to improve - white space. Like I noted before window size on the most of the screenshots can be reduced at least twice horizontally and vertically. Like instead of:

image

you can make:

image

to emphasize on window controls, not white space. Does it make sense?

**Comment by ndonkoHenri** [comment]
Q: Does the uniqueness of the  `className` property doesn't matter ?

**Comment by techemmy** [comment]
> Looks nicer, thank you! And I see you added screenshots to other sections too!
> 
> One last thing to improve - white space. Like I noted before window size on the most of the screenshots can be reduced at least twice horizontally and vertically. Like instead of:
> 
> image
> 
> you can make:
> 
> image
> 
> to emphasize on window controls, not white space. Does it make sense?

Make a lot of sense. Did you use a CSS class name to reduce the size of the screenshot?

**Comment by FeodorFitsner** [comment]
Nope, just resized a real window and took a screenshot.

**Comment by techemmy** [comment]
> Nope, just resized a real window and took a screenshot.

oh, wow! I'll work on that.

**Comment by techemmy** [comment]
> Q: Does the uniqueness of the  `className` property doesn't matter ?

I'm not sure @ndonkoHenri, I think it's just used to specify the size of the image

**Comment by techemmy** [comment]
Hi @FeodorFitsner, do I need to change anything, or can I continue adding more pictures?

**Comment by FeodorFitsner** [comment]
Looks great to me, go on! :)

**Comment by techemmy** [comment]
ok

**Comment by techemmy** [comment]
Screenshot 2022-10-09 at 16 30 58

This sending updates in batches code aims to show the user improvement in scrolling, right?
Should I use a .gif to depict it as you did on the same page earlier, or should I stick with using images?

**Pull request merged**
