### PR TITLE
Added more screenshots for the code examples in the docs 

### PR DESCRIPTION
**Pull request by ndonkoHenri**
I noticed that flet's documentation pages(precisely those on the [controls](https://flet.dev/docs/controls)) lacked sufficient screenshot/captures illustrating what happens when the respective code example is executed.
I thought of running some of the code samples on my PC and created some GIFs and Images. I also added new folders(in the /static/img/docs/controls directory) where i dropped the images/gifs of each respective control.
While editing the markdowns, i tried to use Github's 'Preview' tab, but I wasn't able to see if they were correctly shown/displayed. I can just hope they are.
Those in charge of the website should feel free to edit and fix any error that will occur..(or contact me for any incomprehension)

I hope all this helps the newcomers!

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Alright, gifs are OK now, but what about links to them in `.md` files? ;)

**Comment by ndonkoHenri** [comment]
Thanks @FeodorFitsner! You are awesome. 
I am still learning how to use Git/Github efficiently.
Today you made me learn Cherry-picking.

**Comment by ndonkoHenri** [comment]
@FeodorFitsner ...

**Comment by FeodorFitsner** [comment]
Merge and published in a separate branch that can be seen here: https://more-screenshots.flet-website.pages.dev

**Comment by ndonkoHenri** [comment]
https://more-screenshots.flet-website.pages.dev/docs/controls/filledbutton/#filled-button

The Image is not shown on my browser.
Can you check it?

**Comment by FeodorFitsner** [comment]
Yep, broken image.

**Comment by ndonkoHenri** [comment]
How can I fix that.?

**Comment by FeodorFitsner** [comment]
Remove a link to an image or add an image. Submit a new PR?

**Pull request merged**
