### PR TITLE
feat!: Add Chinese translation

### PR DESCRIPTION
**Pull request by LaoshuBaby**
This PR still a draft, I'll continue to complete it. But maybe I can't work though all page of docs, so if most of paragraphs translated, I suggest you can first merge it then waiting for later fix.

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
I've looked through your first 4 files. Pay attention to the structure - you should not replace the current english text, but additional translations live in `i18n/<language>` folder. Look how to "register" translation in `docusaurus.config.js`: https://github.com/flet-dev/website/pull/9/files#diff-a038096cbdea434999e1dce5ab497212f1fe18204dde1a027ce3bdd663261a2a

image

**Comment by LaoshuBaby** [comment]
@FeodorFitsner another question is should I translate privacy policy? I'm a programmer and cartographer, but not a lawyer. Is there any way auto redirect user to original English privacy policy? (But keep title "privacy policy" translated as "隐私政策")

**Comment by FeodorFitsner** [comment]
Sure, you can just copy original privacy policy to your translation for now.

**Comment by LaoshuBaby** [comment]
@FeodorFitsner 
I do all what I can imitate from Thai version, but looks like the `announcementBar` and `footer` weren't mentioned in this example, and I failed to locate correct key.

### `announcementBar`
图片
图片
图片

### `footer`
图片
图片
图片

**Comment by LaoshuBaby** [comment]
Sorry, there also another problem that if I don't use message as key but assign a key, `translate()` will overwrite English version to that key:

图片
图片
图片

**Comment by FeodorFitsner** [comment]
Hey guys, how are you? Is it still ongoing effort?

**Comment by LaoshuBaby** [comment]
> Hey guys, how are you? Is it still ongoing effort?

I'm alive, and waiting for https://github.com/flet-dev/website/pull/42#issuecomment-1258605397 and https://github.com/flet-dev/website/pull/42#issuecomment-1258615816 's advice 😰

**Comment by FeodorFitsner** [comment]
Ah, right, looking into that! :)

**Comment by LaoshuBaby** [comment]
I can't always wait for reply of above 2 question, so I started docs's translation slowly.
@FeodorFitsner 

---------
Another question：

https://github.com/flet-dev/website/blob/31532bbb0a434337f578a2a5e4100a67781126a1/docs/introduction.md?plain=1#L27

I want to know shall I translation those kind of title in localized version?

If needed, it will be like:
```python
     page.title = "Flet计数器示例" 
```

**Comment by hokaso** [comment]
Wow, this is really a coincidence. Through some ways, I found that my friends are also submitting contributions to Flet. I discussed this isue with my front-end colleague. Classic/*. JSON, that is, the translation of the rich text content of the component of its own framework. Our suggestion is to first translate the content of the translation, and the rest will be said later.

**Comment by LaoshuBaby** [comment]
The complete Translation on docusaurus is too difficult, I quit, the repo will be retained for future reference.

**Comment by hokaso** [comment]
> The complete Translation on docusaurus is too difficult, I quit, the repo will be retained for future reference.

What a pity！

**Comment by jiongjiongJOJO** [comment]
What a pity！

**Pull request closed without merging**
