### PR TITLE
add image for code output for all Python Guide getting started page

### PR DESCRIPTION
**Pull request by techemmy**
[Getting started page](https://flet.dev/docs/guides/python/getting-started)

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
Wouldn't it be necessary to crop the images @techemmy ?

**Comment by FeodorFitsner** [comment]
Could you switch to a light theme please as the rest of the screenshots?

**Comment by techemmy** [comment]
Oh, Light theme. I will switch it to light mode.

> Wouldn't it be necessary to crop the images @techemmy ?

@ndonkoHenri The pictures are cropped.

**Comment by techemmy** [comment]
@FeodorFitsner I also converted images for interactive code to gifs for a better experience. What do you think?

**Comment by FeodorFitsner** [comment]
Merge and published in a separate branch that can be seen here: https://more-screenshots.flet-website.pages.dev/docs/guides/python/getting-started

Imho pics look bulky. Could be more compact, don't you think? And if it's just "Hello, world" in a window you can resize it down to avoid huge white space. Look for the example here: https://more-screenshots.flet-website.pages.dev/docs/

And if you are making a screenshot of a window on Mac please do not cut shadow arround the window - it loses its macOS charm and smoothness without a shadown ;) Example here: https://more-screenshots.flet-website.pages.dev/docs/

**Comment by techemmy** [comment]
Oh, got it. I couldn't find a way of recording videos for gif on macOS without having to cut around its window. Please, do you know any?

**Comment by FeodorFitsner** [comment]
I think we could be OK with static images.

**Comment by techemmy** [comment]
Alright. Then, I'll update the gifs back to static images.

**Pull request merged**
